### ISSUE TITLE
USER STORY: PostgreSQL Database

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#10]
## User Story:
As a **Developer** I can **create and configure a PostgreSQL database for the project** so that **the application can use a reliable production-ready database and allow administrative access in the live environment**

## Acceptance Criteria
- A PostgreSQL dabase has been created on the chosen hosting platform (Heroku) and database credentials are securely stored in the environment variables.
- The project has been configured to use the database in the production settings and to read the PostgreSQL database credentials from the environment variables
- All Django database migrations have been applied successfully.
- The project has been re-deployed successfully, connecting to the new database.

## Tasks
- [x] Create a new PostgreSQL database using the link from Code Institute
- [x] Change the DEBUG setting back to True to allow debugging during development.
- [x] Create an env.py file at the top level of the project. Ensure file has been added to .gitignore.
- [x] In the env.py file, import the operating system module and set the DATABASE_URL constant to the database url.
- [x] Install the required packages to connect to the database and update requirements.txt
- [x] Import the necessary packages in the settings.py file and connect the file to the env.py file.
- [x] Replace the sqlite3 database connection with the new DATABASE_URL environment variable.
- [x] Apply the database migrations to create database tables
- [x] Create a superuser with admin access to the database
- [x] Create a new SECRET_KEY to be added to env.py file as an environment variable.
- [x] Update settings.py file to retrieve the SECRET_KEY from the environment variables.
- [x] Change DEBUG back to false and manually deploy project on Heroku
- [x] Update the Config Vars settings on heroku to ensure the app is connecting to the correct database and to set a SECRET_KEY
