### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#11]
## User Story:
As a **User** I can **use a navigation bar to easily access different sections of the site** so that **I can quickly find and navigate to the content I am interested in**

## Acceptance Criteria
- The navigation bar includes links to the site pages (Home, Blog, About, Contact)
- The navigation bar is consistently displayed accross all pages.
- All links contained in the navigation bar are functional and correctly redirect the user to the corresponding pages.

## Tasks
- [x] Design and incorporate the navigation bar into the base.html file
- [x] Style the navigation bar with CSS and implementing media queries for responsiveness
- [x] Add links and ensure they correctly redirect to the correct page on the site
- [x] Test the links, responsiveness, cross-browser functionality, and accessibility for the nav bar.
- [x] Document the new feature in the README.md
- [x] Document the testing of the new feature in TESTING.md
