### ISSUE TITLE
USER STORY: Site Introduction

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#12]
## User Story:
As a **User** I can **read an introduction to the site** so that **I can understand the purpose of the website and what it offers**.

## Acceptance Criteria
- An introductory section is included in the home page with a clear and friendly description of the site's purpose.
- The introduction is visually distinct and prominently placed on the home page.

## Tasks
- [x] Write engaging content for the introduction and review for any errors.
- [x] Add a new HTML file for the home page template which will link into the base template.
- [x] Include the introduction and add styling for the home page html.
- [x] Test the new feature to ensure the intro is correctly displayed and is responsive for different devices and browsers.
- [x] Test the accessibility of the introduction.
- [x] Document the new feature in README.md
- [x] Document testing of new feature in TESTING.md
