### ISSUE TITLE
USER STORY: Footer & Social Media Links

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#13]
## User Story
As a **User** I can **access social media links in the footer** so that **I can follow the site on social media platforms and stay updated**.

## Acceptance Criteria
- The footer contains recognisable icons including links to the corresponding social media platforms.
- The links are functional and correctly redirect the user to the relevant platform website.
- The footer is consistently displayed accross all pages, and is fixed to the bottom of the page.

## Tasks
- [x] Select and incorporate the icons for each social media platform to be included
- [x] Obtain the correct social media links to be included in the footer.
- [x] Include the footer template within the base.html file and update CSS styling.
- [x] Check the footer is correctly displayed on all pages and is fixed to the bottom of the page.
- [x] Test the responsiveness, browser compatibility, functionality and accessibility of the footer.
- [x] Document the new feature in README.md
- [x] Document the testing of the new feature in TESTING.md
