### ISSUE TITLE
USER STORY: Most Popular Posts

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#14]
## User Story
As a **User** I can **view a section showing the most popular blog posts** so that **I can quickly find and read the most engaging content**.

## Acceptance Criteria
- A section is included on the home page to display a list of the most popular blog posts.
- The section updates dynamically based on the popularity of the blog posts which is determined based on a defined metric (number of views/liked/comments)
- The section includes lnks to the full blog posts for futher reading if selected.

## Tasks
- [x] Decide on the layout and appearance of the popular posts section (list or grid)
- [x] Ensure the blog post model has fields to track popularity. 
- [x] Write the logic to retrieve and sort the most popular posts based on the defined metric.
- [x] Add the HTML required for the popular posts section to the home page html file and add CSS styling.
- [x] Using Django template tags, dynamically display the popular posts.
- [x] Test the functionality, dynaminc updates, accessibility and visual display of the new feature.
- [x] Document the new feature in README.md
- [x] Document the testing of the new feature in TESTING.md
