### ISSUE TITLE
USER STORY: Live Update of Popular Posts

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#15]
## User Story:
As a **User** I can **see the most popular blog posts updated in real time** so that **I always have access to the latest trending content**.

## Acceptance Criteria
- The list of popular posts updated automatically based on recent data
- The updates are made with minimal delay to ensure the presented information remains current.
- Any changes in the list are accurately presented on the home page within the Popular Posts section.

## Tasks
- [x] Utilise Javascript for live updates
- [x] Integrate the live update functionality within the popular posts section on the home page.
- [x] Test the feature to ensure the popular posts section reflects the latest data in real time.
- [x] Check the performance of the home page is not negatively impacted by the new feature.
- [x] Document new feature on README.md
- [x] Document testing of new feature on TESTING.md
