### ISSUE TITLE
USER STORY: Responsive Design

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#16]
## User Story
As a **User** I can **view each page of the site on different devices/browsers** so that **I have consistent and user-friendly experiences with the site regardless of the device/browser I use**

## Acceptance Criteria
- The layout on all pages is responsive and adjusts as appropriate for different screen sizes.
- All elements are displaying correctly and are acceddible on various devices
- There are no errors present when testing each page

## Tasks
- [x] Use media queries within CSS to ensure all elements are responsive
- [x] Modify any elements as may be applicable to ensure they adjust for smaller screens correctly.
- [x] Test the pages on various devices, screen sized and browsers to ensure responsiveness
- [x] Document the responsive design approach and any specific breakpoints within the README.md
- [x] Document the testing completed wihtin the TESTING.md
