### ISSUE TITLE
USER STORY: Accessibility Considerations

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#17]
## User Story:
As a **User with accessibility needs** I can **navigate and interact with the site using assistive technologies** so that **I can access all site content effectively**.

## Acceptance Criteria
- All site pages meet basic accessibility standards (WCAG)
- Navigation elements, links, and content are all accesible using keyboard navigation and screen readers
- Text contrast and font sizes are adjusted for readability.

## Tasks
- [x] Implement keyboard navigation accessibility features
- [x] Add ARIA atrributes or other enhancements for better screen reader support
- [x] Using WAVE test the accedibility of the site and address any issues.
- [x] Perform manual testing of site accessibility using assistive technology (e.g. screen reader)
- [x] Document accessibility features within README.md
- [x] Document accessibility testing within TESTING.md
