### ISSUE TITLE
USER STORY: Blog Posts Display

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#18]
## User Story
As a **User** I can **view a list of blog posts on the blog page** so that **I can read and explore the content created by other users**

## Acceptance Criteria
- The blog page clearly displays a list of blog posts
- Each post displayed will show a title, author details, summary or excerpt, and a link to view the full post.
- Posts are displayed in chronological order, or as defined by a sorting/filtering criterion

## Tasks
- [x] Design and implement a HTML template for the blog page, including placeholdersfor blog posts and other elements as applicable.
- [x] Create django view logic to fetch and display blog posts from the database.
- [x] Ensure the view is able to handle sorting and filtering as required.
- [x] Add a url pattern to route requests to the blog page view.
- [x] Add CSS styling to the blog page consistent with the remainder of the site.
- [x] Test the functionality of the blog page and ensure it is correctly displaying a list of published posts. 
- [x] Check pagination works correctly.
- [x] Document the new features on the README.md
- [x] Document the testing of the new features on the TESTING.md
