### ISSUE TITLE
USER STORY: Liking a Post

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#19]
## User Story
As a **Registered User** I can **like a blog post** so that **I can show my appreciation for content that I enjoy**.

## Acceptance Criteria
- Each blog post includes a 'like' button/link.
- Registered Users are able to like a post, and the like count will automatically update.
- Each post can only be liked once per user, and the button/link will update accordingly to show if a post has already been liked by the user.

## Tasks
- [x] Create and design a button/link to be included in the blog post template.
- [x] Write the django view logic to handle like actions, such as the increment in the like count
- [x] Update the blog post model to include a field for storing the number of likes on each post.
- [x] Creat a url pattern to handle to like requests.
- [x] Implement JavaScript to handle asynchronous like actions
- [x] Test the functionality of the like button so that it changes if a post is already liked, only registered users can like, and it works correctly in updating the like count.
- [x] Document the new feature in README.md
- [x] Document the testing of the new feature in TESTING.md
