### ISSUE TITLE
USER STORY: View/Edit/Save/Delete Posts (Registered User)

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#20]
## User Story
As a **Registered User** I can **view, edit, save and delete my own blog posts** so that **I can manage my content on the blog page**.

## Acceptance Criteria
- Users can view their own blog posts on the blog page.
- Users can edit and save any changes they make to their own blog posts.
- Users can delete their own blog posts removing the post from the list of blog posts for all users.
- Users cannot edit or delete posts which have been created by other users.

## Tasks
- [x] Add options to view, edit, save and delete posts in the blog page template for posts created by a logged-in user.
- [x] Implement the Django views to handle post editing and deletion.
- [x] Update the URL patterns for editing and deleting posts.
- [x] Create forms for editing blog posts which include confirmation dialogues or pages for editing/deleting posts.
- [x] Implement appropriate permissions in the view logic to ensure users can only manage their own posts.
- [x] Test that users can successfully view, edit, save and delete their own posts seperate to the blog post list.
- [x] Verify that users cannot manage posted created by other users.
- [x] Document the new feature in the README.md
- [x] Document the testing of the new feature in TESTING.md
