### ISSUE TITLE
USER STORY: Blog Posts Admin Access

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#21]
## User Story
As an **Admin** I can **delete blog posts that are deemed inappropriate** so that **I can maintain control over the content on the site and ensure the blog content remains suitable and compliant with site policies**.

## Acceptance Criteria
- The superuser admin has the ability to delete any blog posts from the admin interface for the project.
- Deleted posts are removed from the blog page and cannot be accessed by users.

## Tasks
- [x] Integrate the project with Django's admin interface for deleting posts.
- [x] Write the logic required to allow superusers the ability to delete posts from the admin interface.
- [x] Test the deletion of posts using the superuser admin interface and that the posts are no longer visible on the blog page.
- [x] Document the new feature in the README.md
- [x] Document the testing of the new feature in the TESTING.md
