### ISSUE TITLE
USER STORY: Comment on Blog Posts

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#22]
## User Story
As a **Registered User** I can **comment on blog posts** so that **I can share my thoughts or feedback on the content**.

## Acceptance Criteria
- Each blog post has a section for registered users to add comments.
- Users can submit a comment containing text.
- Comments are displayed in chronological order under the respective blog post.
- Users will receive a notification after submitting a comment.

## Tasks
- [x] Design and implement a form for users to submit comments within the blog post template.
- [x] Comment form must include fields for text input
- [x] Write the Django view logic to handle comment submissions ensuring the comemnts are associated with the correct blog post and user.
- [x] Add the URL patters to handle comment submission requests.
- [x] Add CSS styling for the comments section to include comment boxes
- [x] Test the functionality of the comment function to verify users can submit comments.s.
- [x] Check that any submitted comments are displaying correctly under the relevant blog post.
- [x] Document the new feature within the README.md
- [x] Document the testing of the new feature within the TESTING.md
