### ISSUE TITLE
USER STORY: Edit/Delete Comments

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#23]
## User Story
As a **Registered User** I can **edit and delete my own comments** so that **I can correct any mistakes or remove comments if needed**.

## Acceptance Criteria
- Users can access options to edit or delete their own comments.
- Users can edit the text, emoji's and/or GIFs included in their comments.
- Users can delete their own comments, and any deleted comments are removed from the blog post.
- Users are not able to edit or delete any comments created by another user.

## Tasks
- [ ] Include options for editing and deleting comments in the comments section, ensuring the option is only available to the comment author.
- [x] Write the Django view logic to handle comment editing and deletion.
- [x] Update the comment model to allow editing and tracking of changes.
- [x] Add the URL patters required for editing and deleting comments
- [ ] Test that users can successfully edit, save changes or delete their own comments.
- [ ] Test that users cannot edit or delete comments made by other users.
- [ ] Ensure any deleted comments are no longer visible in the comment sections.
- [ ] Document the new feature in the README.md
- [ ] Document the testing of the new feature in the TESTING.md
