### ISSUE TITLE
USER STORY: Comments on Existing Comments

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#24]
## User Story
As a **Registered User** I can **comment on existing comments made by myself or other users** so that **I can reply to or discuss other user's comments on a post**.

## Acceptance Criteria
- Users can reply to existing comments, creating nested comments on each post.
- Comment replies are displayed under the parent comment in a nested format.
- Users can include text, emojis and/or GIFs in their replies.

## Tasks
- [x] Design and update the comment form to support replies to existing comments.
- [x] Amend the comment model to handle parent-child relationships between comments.
- [x] Adjust the comments section display to show replies nested under their relevant parent comments.
- [x] Style the nested comments to distinguish between the levels of comments.
- [ ] Test that users can successfully reply to comments and any replies are displayed correctly in a nested format.
- [ ] Document the new feature in the README.md
- [ ] Document the testing of the new feature in the TESTING.md
