### ISSUE TITLE
USER STORY: Liking a Comment

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#25]
## User Story
As a **Registered User** I can **like other users' comments/replies** so that **I can show my appreciation for any comments I find to be valuable or interesting**.

## Acceptance Criteria
- Each comment/reply has a like button/link which is easy for a user to locate.
- Users can like a comment/reply and the like count updates accordingly.
- Users can only like a comment once.

## Tasks
- [x] Design and add a like button/link for each comment which is visually consistent with the remainder of the site.
- [x] Write the Django view logic to handle like actions for comments.
- [x] Update the comment model to include a field for tracking likes.
- [x] Implement JavaScript to handle asynchronous like actions.
- [ ] Test the like button/link functionality and check the like count adjusts correctly.
- [ ] Check that users are only able to like a comment/reply once.
- [ ] Document the new feature in the README.md
- [ ] Document the testing of the new feature in the TESTING.md
