### ISSUE TITLE
USER STORY: Comments Admin Access

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#26]
## User Story
As an **Admin** I can **delete comments that are deemed inapprpriate** so that **the blog content remains suitable and compliant with site policies**.

## Acceptance Criteria
- A superuser admin can delete any comments via the admin interface of the project.
- Deleted comments are removed from the blog post and cannot be accessed by users.

## Tasks
- [x] Integrate with the Django admin interface for deleting comments.
- [x] Write the logic to allow superusers the ability to delete comments via the admin interface
- [x] Test that superusers can successfully delete comments, and the deleted comments are no longer visible on the blog page/within the comment section.
- [x] Document the new feature within the README.md
- [x] Document the testing of the new feature within the TESTING.md
