### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#27]
## User Story
As a **New User** I can **register for an account** so that **I can access personalised features and interact with blog posts**.

## Acceptance Criteria
- A registration form is available for users to sign up for an account.
- Users must provide a username, email address and password in order to register for their account.
- The system validates input given by a user and ensures that any username/email given is unique and not already in use.
- Users must receive a confirmation message after successful registration
- Passwords must be securely hashed before storage in the database for additional security.

## Tasks
- [x] Design and implement a registration form with fields for username, email and password input.
- [x] Include form validation to ensure input is acceptable.
- [x] Write the Django view logic to handle registration requests and to ensure usernames & emails are unique.
- [x] Use the Django built-in user model and implement password hashing using the Django authentication framework.
- [x] Display confirmation messages on successful registration and handle registration failure errors correctly.
- [x] Test new users can register with unique details, and that any errors are handled appropriately.
- [x] Document the new feature in the README.md
- [x] Document the testing of the new feature in TESTING.md
