### ISSUE TITLE
USER STORY: User Log In

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#28]
## User Story
As a **Registered User** I can **log in to my account** so that **I can access personlised features and manage my content**.

## Acceptance Criteria
- A log in form is available for users to enter their credentials and log in to their account.
- Users must provide a valid username/email and password before being able to log in.
- The system must verify the credentials given and allow user login if input is verified to be correct.
- Users are to receive a confirmation upon successful log in, and any errors are handled appropriately.

## Tasks
- [x] Design and implement the login form to include fields for username/email and password.
- [x] Write the django logic to handle login requests and authenticate the users.
- [x] Use the appropriate framework to maintain user login states.
- [x] Create a message to display to the user on successful log in and handle any errors correctly.
- [x] Test that users can log in sucessfully when using the correct details, and that errors are handled appropriately.
- [x] Document the new feature in the README.md
- [x] Document the testing of the new feature in the TESTING.md
