### ISSUE TITLE
USER STORY: User Log Out

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#29]
## User Story
As a **Logged-In User** I can **log out of my account** so that **my session is terminated and I am securely logged out of my account**.

## Acceptance Criteria
- A logout option is presented and available to logged in users.
- The logging out function ends the user's session and redirects them to the home page of the site.
- User receives a confirmation message on successful logout.

## Tasks
- [x] Write the django view logic to handle logout requests and end the user session.
- [x] Add a URL pattern for the logout view
- [x] Create a message to display to the user when sucessfully logging out, or to handle errors when applicable
- [x] Test that a user can successfully log out of their account, received the corresponding notification and is redirected to the homepage.
- [x] Document the new feature in the README.md
- [x] Document the testing of the new feature in the TESTING.md
