### ISSUE TITLE
USER STORY: Non-Verified User Notifications

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#30]
## User Story:
As a **Logged Out/Unregistered User** I **receive notifications when attempting to comment, like or add a blog post** so that **I am invited to register or log in to access the features**.

## Acceptance Criteria
- When a non-registered or logged out user attempts to comment, like or add a post they are prompted to log in or register for an account.
- Notifications provide clear instructions to the user on how to register or log in
- Users are redirected to the login/register page upon receiving the notification.

## Tasks
- [x] Design and implement the notification messages/modals promting the user to register or log into their account.
- [x] Implement logic to detect non-registred users attempting to perform unauthorised actions.
- [x] Ensure the user is redirected to the login/register page when they attempt to comment, like or add a post.
- [x] Design the notification messages to be clear and engaging.
- [x] Test that notifications are correctly displayed when a user attempts to access an unauthorised action, and all redirection works as expected.
- [x] Document the new feature in the README.md
- [x] Document the testing of the new feature in the TESTING.md
