### ISSUE TITLE
USER STORY: Reset Password

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#31]
## User Story
As a **Registered User** I can **reset my password if I forget it** so that ** I can regain access to my account**.

## Acceptance Criteria
- An option to reset the password is displayed to the user on the login page.
- Users can requeste a password reset link to arrive via email.
- Users receive the reset password email which contains a secure link to reset their password.
- Using the link provided, users can create a new passowrd which will update in the system and allow for successful log in.

## Tasks
- [ ] Implement a form for requesting a passowrd reset email, and a seperate form for creating the new password.
- [ ] Use the build-in Django password reset framework to handle reset requests and link generation.
- [ ] Configue email settings to send password reset links when required.
- [ ] Test the reset functionality to make sure when details are verified an email with a reset link is sent to the correct user email.
- [ ] Test the link in the email correctly redirects to the form to create a new password, and that the new password is correctly updated to allow user log in.
- [ ] Document the new feature in the README.md
- [ ] Document the testing of the new feature in the TESTING.md
