### ISSUE TITLE
USER STORY: User Profile Management

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#32]
## User Story
As a **Registered User** I can **manage my profile information** so that **I can update my personal data and preferences**.

## Acceptance Criteria
- Users can view and update their profile information (e.g. username, email, profile picture)
- Users can change their password from the profile management page.
- Any changes made by the user are saved and reflected in the user's account.

## Tasks
- [ ] Design and implement a form that allows profile information to be updated and the ability to change a user's password.
- [ ] Write the Django veiw logic to handle profile updates and password changes.
- [ ] Add the URL patterns for profile management views.
- [ ] Test that users can successfully update their details, change their passwords, and the updated information is correctly shown on their profile.
- [ ] Document the new feature in the README.md
- [ ] Document the testing of the new feature in the TESTING.md
