### ISSUE TITLE
USER STORY: Search Blog Posts

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#33]
## User Story
As a **User** I can **search for blog posts using a search bar** so that **I can easily find posts that match my interests or query**.

## Acceptance Criteria
- A search bar is available and clearly displayed on the blog page 
- Users can enter keywords into the search bar to find relevant blog posts.
- The results display posts containing the keywords, with the matching words highlighted to indicate relevance to the search
- If no posts match the search criteria a message will display to the user confiming no results were found and encouraging the user to try again with different keywords.

## Tasks
- [ ] Design and implement a search bar to appear on the blog page (and if time as part of the site-wide header/footer)
- [ ] Write the django view logic to handle search queries and return the relevant blog posts. 
- [ ] Integrate with the blog post model to perform text-based searches.
- [ ] Implement the logic required to highlight the search keywords in the results present.
- [ ] Create a template to display the search results with the highlighted keywords.
- [ ] Include pagination if the search returns a high number of results.
- [ ] Create a display message to appear when there are no matching posts for the search query. Should suggest alternative keywords are used or the search needs to be refined.
- [ ] Add the CSS styling for the search bar and highlighted keywords to show in the post results.
- [ ] Test that the search function returns the relevant posts based on the keywords given and that the keywords are correctly highlighted in the results.
- [ ] Test that the correct message appears when no posts can be found in connection with the search query.
- [ ] Document the new features in the README.md
- [ ] Document the testing of the new features in the TESTING.md
