### ISSUE TITLE
USER STORY: README.md

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#35]
## User Story
As a **Developer** I can **complete a README.md file** so that **the project documentation is clear, comprehensive, and provides all necessary information to reviewers and future developers**.

## Acceptance Criteria
- The README.md file contains an overview of the project, it's purpose, and key features.
- Instructions for setting up the development environment, installing dependancies and running the project locally are included.
- Screenshots and examples are provided to enhance understanding.
- Links to any additional documentation or resources are included.
- All required information about the project has been clearly and comprehensively documented.

## Tasks
Include and complete the following sections:
- [x] Am I Responsive Image of Final Project
- [x] Project Overview
- [x] UX Section
- [x] Agile Methodology
- [x] Existing & Potential Features
- [x] Responsive Layout & Design
- [x] Tools Used
- [x] Testing
- [x] Deployment
- [x] Credits
- [x] Acknowledgements

Other Tasks:
- [x] Spell check, check formatting and complete final review of README.md before final submission.
