### ISSUE TITLE
USER STORY: TESTING.md

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#36]
## User Story
As a **Developer** I can **complete a TESTING.md file** so that **reviewers can understand the testing approach, coverage and results for the project**.

## Acceptance Criteria
- The TESTING.md file provides a clear overview of the testing strategy and approach used in the project.
- Detailed desriptions of the tests performed are included.
- The results of manual testing are documentated, including steps to reproduce the test cases.
- Coverage reports or summaries are provided to demonstrate the extent of any automated testing included in the project.
- Any known limitations, issues or unfixed bugs are mentioned.

## Tasks
- [x] Include a general overview of the testing strategy adopted and types of testing performed for the project.
- [x] Document a summary of the automated tests written for the project, including the features & components covered by each test,
- [x] Document the manual testing process, including test cases, expected outcomes and actual results for each test.
- [x] Include information about the test coverage and any coverage reports generated during the project testing.
- [x] Document any known issues, limitations, unfixed bugs, or arears in need of further testing.
- [x] Document code validation testing, including screenshots of the results
- [x] Document responsiveness testing completed
- [x] Document browser compatibility testing completed
- [x] Document User Story Validation
- [x] Review the TESTING.md file, complete proof reading and final review ready for project submission.
