### ISSUE TITLE
USER STORY: Clean Up Code

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#37]
## User Story
As a **Developer** I can **clean up the code workspace by removing commented-out code and unused files** so that **the project is clean, professional and easy to maintain**.

## Acceptance Criteria
- All commented-out code has been removed from the codebase.
- Any unused files, functions and imports have been deleted
- All code is properly formatted, and follows coding standards and best practices.
- The codebase is organised and free of unecessary clutter.

## Tasks
- [x] Remove any commented-out code that is not required.
- [x] Identify and delete any unused files, functions or imports not required for the final project functionality.
- [x] Check all code is correctly formatted.
- [x] Perform a final check to ensure the codebase is clean and free from any unecessary code.
