### ISSUE TITLE
USER STORY: Final Project Review

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#39]
## User Story
As a **Developer** I can **perform a final review of the project** so that **it is fully prepared for submission and assessment**.

## Acceptance Criteria
- All user stories and features are implemented and functional
- The codebase is clean, well-documented, and follows coding standards
- The project passess all tests, and the testing documentation is complete.
- The final version of the project has been deployed and is accessible in the production environment.
- The README.md and TESTING.md are comprehensive, completed and up to date.

## Tasks
- [x] Verify all user stories have been completed and features work as intended.
- [x] Check the documentation is complete and accurate.
- [x] Run all automated and manual tests to ensure the project is error-free
- [x] Review the codebase for any last minute adjustments or improvements
- [x] Check the Assessment Criteria to ensure all objectives have been met.
- [x] Prepare and submit the project in accordance to the Code Institute guidelines.
