### ISSUE TITLE
USER STORY: Django Set Up

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#8]
## User Story:
As a **Developer**, I can **set up a Django project base structure with the neccessary configurations and initial app setup** so that **I can efficiently implement and test the required features for the project**

## Acceptance Criteria
- A new Django project is created with a clearly defined project structure, including the necessary apps for the project (e.g. core, blog, comments).
- A base.html template has been set up with a consistent structure ready to be used accross the application.
- Basic URL routing has been fixed to include a main URL configuration file and initial placeholder views for each app.
- Static and media file handling is set up with the appropriate directories in place.
- A testing framework has been created with at lest one basic test to ensure project runs correctly.
- The project is initialised with version control (Git) with an initial commit containing the base structure

## Tasks
- [x] Create new workspace on the IDE
- [x] Install Django via the package manager
- [x] Create requirements.txt file and add installed packages
- [x] Create a new project named 'cleaning_blog'
- [x] Create required apps for the project: core, blog, comments, users.
- [x] Update settings.py file to include the newly created apps to "INSTALLED APPS"
- [x] In each views.py files add the required import statement and add a temporary function to display text
- [x] In the project urls.py file import the required views and add new paths to the urlpatterns.
- [x] Update the ALLOWED_HOSTS in the settings.py file to include the hostname.
- [x] Create and organise the apps and file directories required for the project
- [x] Create base.html page to act as the template for static pages required, ensure all apps reference the base template.
- [x] Set up a testing framework to include at least 1 basic test.
- [x] Run the server in the browser window to test the code and confirm text is displayed correctly.
