### ISSUE TITLE
USER STORY: Early Deployment

### ISSUE THREAD

**Issue by TonichaB** [TonichaB/cleaning-blog#9]
## User Story
As a **Developer** I can **set up the project for early deployment** so that **I can quickly deploy the application to a live environment and gather initial feedback and test the production environment throughout development**

## Acceptance Criteria
- The project uses environment variables to manage sensitive date, and setting have been configured to distinguish between the development and production environments.
- Production dependencies (gunicorn) have been installed for WSGI server handling, and requirements.txt is up to date with all installed dependencies.
- A Procfile is created to specify the commands required for the application to be run on the deployment platform
- The project is set up to comply with the requirements of the deployment platform (Heroku), and initial deployment to the platform is successful.

## Tasks
- [x] Create a new app on the Heroku Dashboard
- [x] Update the Config Var settings in the app settings tab on heroku. 
- [x] Install gunicorn webserver and update requirements.txt file
- [x] Create Procfile within the root directory and add command to start the webserver
- [x] Set DEBUG in settings.py file to false prior to deployment and ensure heroku url added to ALLOWED_HOSTS
